// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

public partial class CApp_SystemApp_System_BancobancoSQLitedbContext : DbContext
{
    public CApp_SystemApp_System_BancobancoSQLitedbContext(DbContextOptions<CApp_SystemApp_System_BancobancoSQLitedbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TbAtor> TbAtor { get; set; }

    public virtual DbSet<TbCategoriaProduto> TbCategoriaProduto { get; set; }

    public virtual DbSet<TbCertificadoDigital> TbCertificadoDigital { get; set; }

    public virtual DbSet<TbClasCont1> TbClasCont1 { get; set; }

    public virtual DbSet<TbClasCont2> TbClasCont2 { get; set; }

    public virtual DbSet<TbCodigoProduto> TbCodigoProduto { get; set; }

    public virtual DbSet<TbCont> TbCont { get; set; }

    public virtual DbSet<TbContExt> TbContExt { get; set; }

    public virtual DbSet<TbContExtGru> TbContExtGru { get; set; }

    public virtual DbSet<TbContExtSec> TbContExtSec { get; set; }

    public virtual DbSet<TbContExtSubGru> TbContExtSubGru { get; set; }

    public virtual DbSet<TbContGru> TbContGru { get; set; }

    public virtual DbSet<TbContSec> TbContSec { get; set; }

    public virtual DbSet<TbContSubGru> TbContSubGru { get; set; }

    public virtual DbSet<TbEst> TbEst { get; set; }

    public virtual DbSet<TbEstadosBr> TbEstadosBr { get; set; }

    public virtual DbSet<TbFormaPagamento> TbFormaPagamento { get; set; }

    public virtual DbSet<TbHistorico> TbHistorico { get; set; }

    public virtual DbSet<TbJornada> TbJornada { get; set; }

    public virtual DbSet<TbMarcaProduto> TbMarcaProduto { get; set; }

    public virtual DbSet<TbMatriz> TbMatriz { get; set; }

    public virtual DbSet<TbMovimentacao> TbMovimentacao { get; set; }

    public virtual DbSet<TbMovimentacaoCaixa> TbMovimentacaoCaixa { get; set; }

    public virtual DbSet<TbMovimentacaoImpressao> TbMovimentacaoImpressao { get; set; }

    public virtual DbSet<TbMovimentacaoPagamento> TbMovimentacaoPagamento { get; set; }

    public virtual DbSet<TbMovimentacaoPagamentoParcela> TbMovimentacaoPagamentoParcela { get; set; }

    public virtual DbSet<TbMovimentacaoProduto> TbMovimentacaoProduto { get; set; }

    public virtual DbSet<TbMunicipio> TbMunicipio { get; set; }

    public virtual DbSet<TbNcm> TbNcm { get; set; }

    public virtual DbSet<TbNfe> TbNfe { get; set; }

    public virtual DbSet<TbNfeEnviadaFilial> TbNfeEnviadaFilial { get; set; }

    public virtual DbSet<TbPais> TbPais { get; set; }

    public virtual DbSet<TbPdv> TbPdv { get; set; }

    public virtual DbSet<TbPlanCont> TbPlanCont { get; set; }

    public virtual DbSet<TbProduto> TbProduto { get; set; }

    public virtual DbSet<TbProdutoFilial> TbProdutoFilial { get; set; }

    public virtual DbSet<TbRede> TbRede { get; set; }

    public virtual DbSet<TbRegioesBr> TbRegioesBr { get; set; }

    public virtual DbSet<TbRelacaoProdutoCadastroXml> TbRelacaoProdutoCadastroXml { get; set; }

    public virtual DbSet<TbResEventoNfe> TbResEventoNfe { get; set; }

    public virtual DbSet<TbRespostaNfe> TbRespostaNfe { get; set; }

    public virtual DbSet<TbSecaoProduto> TbSecaoProduto { get; set; }

    public virtual DbSet<TbSubFormaPagamento> TbSubFormaPagamento { get; set; }

    public virtual DbSet<TbSubcategoriaProduto> TbSubcategoriaProduto { get; set; }

    public virtual DbSet<TbUnidadeMonetaria> TbUnidadeMonetaria { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}