// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_ator")]
[Index("FkTbCertificadoDigital", Name = "ifk_tb_certificado_digital_tb_ator")]
[Index("FkTbEstadosBr", Name = "ifk_tb_estados_br_tb_ator")]
[Index("FkTbMatriz", Name = "ifk_tb_matriz_tb_ator")]
[Index("FkTbMunicipio", Name = "ifk_tb_municipio_tb_ator")]
public partial class TbAtor
{
    [Key]
    [Column("id_ator")]
    public int IdAtor { get; set; }

    [Column("at_inscEstSubst", TypeName = "varchar(20)")]
    public string AtInscEstSubst { get; set; }

    [Column("at_persTim", TypeName = "tinyint")]
    public byte AtPersTim { get; set; }

    [Column("at_dirRede", TypeName = "tinyint")]
    public byte AtDirRede { get; set; }

    [Column("at_dirMov", TypeName = "tinyint")]
    public byte AtDirMov { get; set; }

    [Column("at_dtCri", TypeName = "DATETIME")]
    public DateTime AtDtCri { get; set; }

    [Column("at_dtAlt", TypeName = "DATETIME")]
    public DateTime AtDtAlt { get; set; }

    [Column("at_dtAcs", TypeName = "DATETIME")]
    public DateTime? AtDtAcs { get; set; }

    [Column("at_desat", TypeName = "NUMERIC(1, 0)")]
    public int? AtDesat { get; set; }

    [Column("at_genero", TypeName = "tinyint")]
    public byte AtGenero { get; set; }

    [Column("at_nfeIndInscEst", TypeName = "tinyint")]
    public byte AtNfeIndInscEst { get; set; }

    [Column("at_nfeCodRegTrib", TypeName = "tinyint")]
    public byte AtNfeCodRegTrib { get; set; }

    [Column("at_atorTipo", TypeName = "tinyint")]
    public byte AtAtorTipo { get; set; }

    [Column("at_cnpj", TypeName = "varchar(18)")]
    public string AtCnpj { get; set; }

    [Column("at_cpf", TypeName = "varchar(14)")]
    public string AtCpf { get; set; }

    [Column("at_rgRne", TypeName = "varchar(20)")]
    public string AtRgRne { get; set; }

    [Column("at_idMl", TypeName = "varchar(60)")]
    public string AtIdMl { get; set; }

    [Column("at_razSoc", TypeName = "varchar(60)")]
    public string AtRazSoc { get; set; }

    [Column("at_nomeFant", TypeName = "varchar(60)")]
    public string AtNomeFant { get; set; }

    [Column("at_end_Logr", TypeName = "varchar(60)")]
    public string AtEndLogr { get; set; }

    [Column("at_end_Num", TypeName = "varchar(60)")]
    public string AtEndNum { get; set; }

    [Column("at_end_Compl", TypeName = "varchar(60)")]
    public string AtEndCompl { get; set; }

    [Column("at_end_Bairro", TypeName = "varchar(60)")]
    public string AtEndBairro { get; set; }

    [Column("at_end_PontoRef")]
    public string AtEndPontoRef { get; set; }

    [Column("at_end_Cep", TypeName = "varchar(9)")]
    public string AtEndCep { get; set; }

    [Column("at_end_Mun", TypeName = "INTEGER")]
    public Guid? AtEndMun { get; set; }

    [Column("at_telFixo", TypeName = "varchar(20)")]
    public string AtTelFixo { get; set; }

    [Column("at_telFixoRamal", TypeName = "varchar(10)")]
    public string AtTelFixoRamal { get; set; }

    [Column("at_telCel", TypeName = "varchar(20)")]
    public string AtTelCel { get; set; }

    [Column("at_respon", TypeName = "varchar(60)")]
    public string AtRespon { get; set; }

    [Column("at_inscEst", TypeName = "varchar(20)")]
    public string AtInscEst { get; set; }

    [Column("at_inscMun", TypeName = "varchar(20)")]
    public string AtInscMun { get; set; }

    [Column("at_inscSuframa", TypeName = "varchar(9)")]
    public string AtInscSuframa { get; set; }

    [Column("at_email", TypeName = "varchar(60)")]
    public string AtEmail { get; set; }

    [Column("at_website", TypeName = "varchar(60)")]
    public string AtWebsite { get; set; }

    [Column("at_dtNasc", TypeName = "varchar(5)")]
    public string AtDtNasc { get; set; }

    [Column("at_emailCont", TypeName = "varchar(60)")]
    public string AtEmailCont { get; set; }

    [Column("at_obsCom")]
    public string AtObsCom { get; set; }

    [Column("at_obsFisc")]
    public string AtObsFisc { get; set; }

    [Column("at_cnae", TypeName = "varchar(12)")]
    public string AtCnae { get; set; }

    [Column("at_prop", TypeName = "NUMERIC(1, 0)")]
    public int? AtProp { get; set; }

    [Column("at_nfeCredSn", TypeName = "NUMERIC(13, 2)")]
    public int? AtNfeCredSn { get; set; }

    [Column("at_nfeCscTokenProd", TypeName = "varchar(100)")]
    public string AtNfeCscTokenProd { get; set; }

    [Column("at_nfeCscIdProd", TypeName = "tinyint")]
    public byte AtNfeCscIdProd { get; set; }

    [Column("at_nfeCscTokenHom", TypeName = "varchar(100)")]
    public string AtNfeCscTokenHom { get; set; }

    [Column("at_nfeCscIdHom", TypeName = "tinyint")]
    public byte AtNfeCscIdHom { get; set; }

    [Column("at_revenda", TypeName = "NUMERIC(1, 0)")]
    public int? AtRevenda { get; set; }

    [Column("at_nfeEnqSN", TypeName = "tinyint")]
    public byte AtNfeEnqSn { get; set; }

    [Column("at_nfeRecBrutaEnqSN", TypeName = "tinyint")]
    public byte AtNfeRecBrutaEnqSn { get; set; }

    [Column("at_receitaBrutaTotal", TypeName = "NUMERIC(13, 2)")]
    public int? AtReceitaBrutaTotal { get; set; }

    [Column("at_receitaBrutaTotal_ImpXml", TypeName = "NUMERIC(13, 2)")]
    public int? AtReceitaBrutaTotalImpXml { get; set; }

    [Column("at_nfeTipoAmb", TypeName = "tinyint")]
    public byte AtNfeTipoAmb { get; set; }

    [Column("at_percComisAtend", TypeName = "NUMERIC(6, 3)")]
    public int? AtPercComisAtend { get; set; }

    [Column("at_metaMensal", TypeName = "NUMERIC(10, 2)")]
    public int AtMetaMensal { get; set; }

    [Column("at_nomeUsuario", TypeName = "varchar(20)")]
    public string AtNomeUsuario { get; set; }

    [Column("at_senhaUsuarioHashCode", TypeName = "varchar(60)")]
    public string AtSenhaUsuarioHashCode { get; set; }

    [Column("at_manutPdv", TypeName = "NUMERIC(1, 0)")]
    public int? AtManutPdv { get; set; }

    [Column("at_atorH")]
    public int? AtAtorH { get; set; }

    [Column("at_estH")]
    public int? AtEstH { get; set; }

    [Column("at_canc", TypeName = "NUMERIC(1, 0)")]
    public int? AtCanc { get; set; }

    [Column("fk_tb_municipio")]
    public int? FkTbMunicipio { get; set; }

    [Column("fk_tb_estados_br")]
    public int? FkTbEstadosBr { get; set; }

    [Column("fk_tb_certificado_digital")]
    public int? FkTbCertificadoDigital { get; set; }

    [Column("fk_tb_matriz")]
    public int? FkTbMatriz { get; set; }

    [ForeignKey("FkTbCertificadoDigital")]
    [InverseProperty("TbAtor")]
    public virtual TbCertificadoDigital FkTbCertificadoDigitalNavigation { get; set; }

    [ForeignKey("FkTbEstadosBr")]
    [InverseProperty("TbAtor")]
    public virtual TbEstadosBr FkTbEstadosBrNavigation { get; set; }

    [ForeignKey("FkTbMatriz")]
    [InverseProperty("TbAtor")]
    public virtual TbMatriz FkTbMatrizNavigation { get; set; }

    [ForeignKey("FkTbMunicipio")]
    [InverseProperty("TbAtor")]
    public virtual TbMunicipio FkTbMunicipioNavigation { get; set; }

    [InverseProperty("FkTbAtorNavigation")]
    public virtual ICollection<TbCertificadoDigital> TbCertificadoDigital { get; set; } = new List<TbCertificadoDigital>();

    [InverseProperty("FkTbAtorNavigation")]
    public virtual ICollection<TbCont> TbCont { get; set; } = new List<TbCont>();

    [InverseProperty("FkTbAtorNavigation")]
    public virtual ICollection<TbHistorico> TbHistorico { get; set; } = new List<TbHistorico>();

    [InverseProperty("FkTbAtorAtendNavigation")]
    public virtual ICollection<TbMovimentacao> TbMovimentacaoFkTbAtorAtendNavigation { get; set; } = new List<TbMovimentacao>();

    [InverseProperty("FkTbAtorDestNavigation")]
    public virtual ICollection<TbMovimentacao> TbMovimentacaoFkTbAtorDestNavigation { get; set; } = new List<TbMovimentacao>();

    [InverseProperty("FkTbAtorEmitNavigation")]
    public virtual ICollection<TbMovimentacao> TbMovimentacaoFkTbAtorEmitNavigation { get; set; } = new List<TbMovimentacao>();

    [InverseProperty("FkTbAtorAtendNavigation")]
    public virtual ICollection<TbMovimentacaoProduto> TbMovimentacaoProduto { get; set; } = new List<TbMovimentacaoProduto>();

    [InverseProperty("FkTbAtorNavigation")]
    public virtual ICollection<TbPdv> TbPdv { get; set; } = new List<TbPdv>();

    [InverseProperty("FkTbAtorNavigation")]
    public virtual ICollection<TbProduto> TbProduto { get; set; } = new List<TbProduto>();

    [InverseProperty("FkTbAtorNavigation")]
    public virtual ICollection<TbProdutoFilial> TbProdutoFilial { get; set; } = new List<TbProdutoFilial>();

    [InverseProperty("FkTbAtorNavigation")]
    public virtual ICollection<TbRelacaoProdutoCadastroXml> TbRelacaoProdutoCadastroXml { get; set; } = new List<TbRelacaoProdutoCadastroXml>();

    [InverseProperty("FkTbAtorNavigation")]
    public virtual ICollection<TbResEventoNfe> TbResEventoNfe { get; set; } = new List<TbResEventoNfe>();

    [InverseProperty("FkTbAtorNavigation")]
    public virtual ICollection<TbRespostaNfe> TbRespostaNfe { get; set; } = new List<TbRespostaNfe>();
}