// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_clasCont2")]
[Index("FkTbPdv", Name = "ifk_tb_pdv_tb_clasCont2")]
public partial class TbClasCont2
{
    [Key]
    [Column("id_clasCont2")]
    public int IdClasCont2 { get; set; }

    [Column("cc2_clasCont1")]
    public int? Cc2ClasCont1 { get; set; }

    [Column("cc2_dtCri", TypeName = "DATETIME")]
    public DateTime Cc2DtCri { get; set; }

    [Column("cc2_dtAlt", TypeName = "DATETIME")]
    public DateTime Cc2DtAlt { get; set; }

    [Column("cc2_dtAcs", TypeName = "DATETIME")]
    public DateTime? Cc2DtAcs { get; set; }

    [Column("cc2_desat", TypeName = "NUMERIC(1, 0)")]
    public decimal? Cc2Desat { get; set; }

    [Column("cc2_desc", TypeName = "varchar(60)")]
    public string Cc2Desc { get; set; }

    [Column("fk_tb_pdv")]
    public int? FkTbPdv { get; set; }

    [ForeignKey("FkTbPdv")]
    [InverseProperty("TbClasCont2")]
    public virtual TbPdv FkTbPdvNavigation { get; set; }

    [InverseProperty("FkTbClasCont2Navigation")]
    public virtual ICollection<TbMovimentacao> TbMovimentacao { get; set; } = new List<TbMovimentacao>();
}