// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_codigo_produto")]
[Index("FkTbProduto", Name = "ifk_tb_produto_tb_codigo_produto")]
public partial class TbCodigoProduto
{
    [Key]
    [Column("id_codigo_produto")]
    public int IdCodigoProduto { get; set; }

    [Column("cp_desat", TypeName = "NUMERIC(1, 0)")]
    public decimal? CpDesat { get; set; }

    [Column("cp_dtCri", TypeName = "DATETIME")]
    public DateTime CpDtCri { get; set; }

    [Column("cp_dtAlt", TypeName = "DATETIME")]
    public DateTime CpDtAlt { get; set; }

    [Column("cp_dtAcs", TypeName = "DATETIME")]
    public DateTime? CpDtAcs { get; set; }

    [Column("cp_barras", TypeName = "varchar(14)")]
    public string CpBarras { get; set; }

    [Column("fk_tb_produto")]
    public int? FkTbProduto { get; set; }

    [ForeignKey("FkTbProduto")]
    [InverseProperty("TbCodigoProduto")]
    public virtual TbProduto FkTbProdutoNavigation { get; set; }
}