// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_est")]
[Index("FkTbMatriz", Name = "ifk_tb_matriz_tb_est")]
public partial class TbEst
{
    [Key]
    [Column("id_est")]
    public int IdEst { get; set; }

    [Column("es_dtCri", TypeName = "DATETIME")]
    public DateTime EsDtCri { get; set; }

    [Column("es_dtAlt", TypeName = "DATETIME")]
    public DateTime EsDtAlt { get; set; }

    [Column("es_dtAcs", TypeName = "DATETIME")]
    public DateTime? EsDtAcs { get; set; }

    [Column("es_dskCaption", TypeName = "varchar(64)")]
    public string EsDskCaption { get; set; }

    [Column("es_dskIndex", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsDskIndex { get; set; }

    [Column("es_dskSerialNumber", TypeName = "varchar(128)")]
    public string EsDskSerialNumber { get; set; }

    [Column("es_dskSignature", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsDskSignature { get; set; }

    [Column("es_dskSize", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsDskSize { get; set; }

    [Column("es_dskStatus", TypeName = "varchar(10)")]
    public string EsDskStatus { get; set; }

    [Column("es_nicAdapterType", TypeName = "varchar(64)")]
    public string EsNicAdapterType { get; set; }

    [Column("es_nicAdapterTypeID", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsNicAdapterTypeId { get; set; }

    [Column("es_nicCaption", TypeName = "varchar(64)")]
    public string EsNicCaption { get; set; }

    [Column("es_nicDescription", TypeName = "varchar(128)")]
    public string EsNicDescription { get; set; }

    [Column("es_nicInterfaceIndex", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsNicInterfaceIndex { get; set; }

    [Column("es_nicMacAddress", TypeName = "varchar(32)")]
    public string EsNicMacAddress { get; set; }

    [Column("es_nicMacAddressVpn", TypeName = "varchar(32)")]
    public string EsNicMacAddressVpn { get; set; }

    [Column("es_nicManufacturer", TypeName = "varchar(64)")]
    public string EsNicManufacturer { get; set; }

    [Column("es_nicName", TypeName = "varchar(128)")]
    public string EsNicName { get; set; }

    [Column("es_nicNetEnabled", TypeName = "NUMERIC(1, 0)")]
    public decimal? EsNicNetEnabled { get; set; }

    [Column("es_nicSpeed", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsNicSpeed { get; set; }

    [Column("es_nicCfgDHCPEnabled", TypeName = "NUMERIC(1, 0)")]
    public decimal? EsNicCfgDhcpenabled { get; set; }

    [Column("es_nicCfgDHCPServer", TypeName = "varchar(48)")]
    public string EsNicCfgDhcpserver { get; set; }

    [Column("es_nicCfgDNSDomain", TypeName = "varchar(255)")]
    public string EsNicCfgDnsdomain { get; set; }

    [Column("es_nicCfgIPAddress")]
    public string EsNicCfgIpaddress { get; set; }

    [Column("es_nicCfgIPAddressVpn")]
    public string EsNicCfgIpaddressVpn { get; set; }

    [Column("es_nicCfgIPConnectionMetric", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsNicCfgIpconnectionMetric { get; set; }

    [Column("es_nicCfgIPEnabled", TypeName = "NUMERIC(1, 0)")]
    public decimal? EsNicCfgIpenabled { get; set; }

    [Column("es_pcPgFlAllocatedBaseSize", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcPgFlAllocatedBaseSize { get; set; }

    [Column("es_pcPgFlCurrentUsage", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcPgFlCurrentUsage { get; set; }

    [Column("es_pcPgFlPeakUsage", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcPgFlPeakUsage { get; set; }

    [Column("es_pcPowInstanceID", TypeName = "varchar(60)")]
    public string EsPcPowInstanceId { get; set; }

    [Column("es_pcPowElementName", TypeName = "varchar(60)")]
    public string EsPcPowElementName { get; set; }

    [Column("es_pcLdCaption", TypeName = "varchar(60)")]
    public string EsPcLdCaption { get; set; }

    [Column("es_pcLdCompressed", TypeName = "NUMERIC(1, 0)")]
    public decimal? EsPcLdCompressed { get; set; }

    [Column("es_pcLdConfigManagerErrorCode", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcLdConfigManagerErrorCode { get; set; }

    [Column("es_pcLdDeviceID", TypeName = "varchar(60)")]
    public string EsPcLdDeviceId { get; set; }

    [Column("es_pcLdDriveType", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcLdDriveType { get; set; }

    [Column("es_pcLdFileSystem", TypeName = "varchar(20)")]
    public string EsPcLdFileSystem { get; set; }

    [Column("es_pcLdFreeSpace", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsPcLdFreeSpace { get; set; }

    [Column("es_pcLdLastErrorCode", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcLdLastErrorCode { get; set; }

    [Column("es_pcLdName", TypeName = "varchar(64)")]
    public string EsPcLdName { get; set; }

    [Column("es_pcLdSize", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsPcLdSize { get; set; }

    [Column("es_pcLdVolumeDirty", TypeName = "NUMERIC(1, 0)")]
    public decimal? EsPcLdVolumeDirty { get; set; }

    [Column("es_pcLdVolumeSerialNumber", TypeName = "varchar(60)")]
    public string EsPcLdVolumeSerialNumber { get; set; }

    [Column("es_pcAutomaticManagedPagefile", TypeName = "NUMERIC(1, 0)")]
    public decimal? EsPcAutomaticManagedPagefile { get; set; }

    [Column("es_pcAutomaticResetBootOption", TypeName = "NUMERIC(1, 0)")]
    public decimal? EsPcAutomaticResetBootOption { get; set; }

    [Column("es_pcAutomaticResetCapability", TypeName = "NUMERIC(1, 0)")]
    public decimal? EsPcAutomaticResetCapability { get; set; }

    [Column("es_pcBootROMSupported", TypeName = "NUMERIC(1, 0)")]
    public decimal? EsPcBootRomsupported { get; set; }

    [Column("es_pcBootupState", TypeName = "varchar(50)")]
    public string EsPcBootupState { get; set; }

    [Column("es_pcCurrentTimeZone", TypeName = "smallint")]
    public short EsPcCurrentTimeZone { get; set; }

    [Column("es_pcDaylightInEffect", TypeName = "NUMERIC(1, 0)")]
    public decimal? EsPcDaylightInEffect { get; set; }

    [Column("es_pcDNSHostName", TypeName = "varchar(255)")]
    public string EsPcDnshostName { get; set; }

    [Column("es_pcDomainRole", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsPcDomainRole { get; set; }

    [Column("es_pcEnableDaylightSavingsTime", TypeName = "NUMERIC(1, 0)")]
    public decimal? EsPcEnableDaylightSavingsTime { get; set; }

    [Column("es_pcHypervisorPresent", TypeName = "NUMERIC(1, 0)")]
    public decimal? EsPcHypervisorPresent { get; set; }

    [Column("es_pcManufacturer", TypeName = "varchar(50)")]
    public string EsPcManufacturer { get; set; }

    [Column("es_pcNetworkServerModeEnabled", TypeName = "NUMERIC(1, 0)")]
    public decimal? EsPcNetworkServerModeEnabled { get; set; }

    [Column("es_pcNumberOfLogicalProcessors", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcNumberOfLogicalProcessors { get; set; }

    [Column("es_pcNumberOfProcessors", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcNumberOfProcessors { get; set; }

    [Column("es_pcPCSystemType", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsPcPcsystemType { get; set; }

    [Column("es_pcTotalPhysicalMemory", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsPcTotalPhysicalMemory { get; set; }

    [Column("es_pcUserName", TypeName = "varchar(255)")]
    public string EsPcUserName { get; set; }

    [Column("es_pcWakeUpType", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsPcWakeUpType { get; set; }

    [Column("es_biosCaption", TypeName = "varchar(64)")]
    public string EsBiosCaption { get; set; }

    [Column("es_biosSerialNumber", TypeName = "varchar(64)")]
    public string EsBiosSerialNumber { get; set; }

    [Column("es_biosSMBIOSBIOSVersion", TypeName = "varchar(64)")]
    public string EsBiosSmbiosbiosversion { get; set; }

    [Column("es_biosSoftwareElementID", TypeName = "varchar(256)")]
    public string EsBiosSoftwareElementId { get; set; }

    [Column("es_boardManufacturer", TypeName = "varchar(256)")]
    public string EsBoardManufacturer { get; set; }

    [Column("es_boardProduct", TypeName = "varchar(64)")]
    public string EsBoardProduct { get; set; }

    [Column("es_boardSerialNumber", TypeName = "varchar(64)")]
    public string EsBoardSerialNumber { get; set; }

    [Column("es_boardStatus", TypeName = "varchar(10)")]
    public string EsBoardStatus { get; set; }

    [Column("es_boardVersion", TypeName = "varchar(64)")]
    public string EsBoardVersion { get; set; }

    [Column("es_pcOsBuildNumber", TypeName = "varchar(10)")]
    public string EsPcOsBuildNumber { get; set; }

    [Column("es_pcOsCaption", TypeName = "varchar(64)")]
    public string EsPcOsCaption { get; set; }

    [Column("es_pcOsCodeSet", TypeName = "varchar(6)")]
    public string EsPcOsCodeSet { get; set; }

    [Column("es_pcOsCountryCode", TypeName = "varchar(256)")]
    public string EsPcOsCountryCode { get; set; }

    [Column("es_pcOsCurrentTimeZone", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsPcOsCurrentTimeZone { get; set; }

    [Column("es_pcOsFreePhysicalMemory", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsPcOsFreePhysicalMemory { get; set; }

    [Column("es_pcOsFreeSpaceInPagingFiles", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsPcOsFreeSpaceInPagingFiles { get; set; }

    [Column("es_pcOsFreeVirtualMemory", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsPcOsFreeVirtualMemory { get; set; }

    [Column("es_pcOsInstallDate", TypeName = "DATETIME")]
    public DateTime? EsPcOsInstallDate { get; set; }

    [Column("es_pcOsLastBootUpTime", TypeName = "DATETIME")]
    public DateTime? EsPcOsLastBootUpTime { get; set; }

    [Column("es_pcOsLocalDateTime", TypeName = "DATETIME")]
    public DateTime? EsPcOsLocalDateTime { get; set; }

    [Column("es_pcOsLocale", TypeName = "varchar(6)")]
    public string EsPcOsLocale { get; set; }

    [Column("es_pcOsNumberOfProcesses", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcOsNumberOfProcesses { get; set; }

    [Column("es_pcOsNumberOfUsers", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcOsNumberOfUsers { get; set; }

    [Column("es_pcOsOperatingSystemSKU", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcOsOperatingSystemSku { get; set; }

    [Column("es_pcOSArchitecture", TypeName = "varchar(10)")]
    public string EsPcOsarchitecture { get; set; }

    [Column("es_pcOSLanguage", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcOslanguage { get; set; }

    [Column("es_pcOSProductSuite", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcOsproductSuite { get; set; }

    [Column("es_pcOsPortableOperatingSystem", TypeName = "NUMERIC(1, 0)")]
    public decimal? EsPcOsPortableOperatingSystem { get; set; }

    [Column("es_pcOsPrimary", TypeName = "NUMERIC(1, 0)")]
    public decimal? EsPcOsPrimary { get; set; }

    [Column("es_pcOsProductType", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcOsProductType { get; set; }

    [Column("es_pcOsRegisteredUser", TypeName = "varchar(100)")]
    public string EsPcOsRegisteredUser { get; set; }

    [Column("es_pcOsSerialNumber", TypeName = "varchar(50)")]
    public string EsPcOsSerialNumber { get; set; }

    [Column("es_pcOsServicePackMajorVersion", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsPcOsServicePackMajorVersion { get; set; }

    [Column("es_pcOsServicePackMinorVersion", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsPcOsServicePackMinorVersion { get; set; }

    [Column("es_pcOsSizeStoredInPagingFiles", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsPcOsSizeStoredInPagingFiles { get; set; }

    [Column("es_pcOsSuiteMask", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcOsSuiteMask { get; set; }

    [Column("es_pcOsSystemDrive", TypeName = "varchar(2)")]
    public string EsPcOsSystemDrive { get; set; }

    [Column("es_pcOsTotalSwapSpaceSize", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsPcOsTotalSwapSpaceSize { get; set; }

    [Column("es_pcOsTotalVirtualMemorySize", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsPcOsTotalVirtualMemorySize { get; set; }

    [Column("es_pcOsTotalVisibleMemorySize", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsPcOsTotalVisibleMemorySize { get; set; }

    [Column("es_pcOsVersion", TypeName = "varchar(20)")]
    public string EsPcOsVersion { get; set; }

    [Column("es_procHandle", TypeName = "varchar(256)")]
    public string EsProcHandle { get; set; }

    [Column("es_procHandleCount", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsProcHandleCount { get; set; }

    [Column("es_procKernelModeTime", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsProcKernelModeTime { get; set; }

    [Column("es_procOtherOperationCount", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsProcOtherOperationCount { get; set; }

    [Column("es_procOtherTransferCount", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsProcOtherTransferCount { get; set; }

    [Column("es_procPageFaults", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsProcPageFaults { get; set; }

    [Column("es_procPageFileUsage", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsProcPageFileUsage { get; set; }

    [Column("es_procPeakPageFileUsage", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsProcPeakPageFileUsage { get; set; }

    [Column("es_procPeakVirtualSize", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsProcPeakVirtualSize { get; set; }

    [Column("es_procPeakWorkingSetSize", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsProcPeakWorkingSetSize { get; set; }

    [Column("es_procPriority", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsProcPriority { get; set; }

    [Column("es_procPrivatePageCount", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsProcPrivatePageCount { get; set; }

    [Column("es_procProcessId", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsProcProcessId { get; set; }

    [Column("es_procReadOperationCount", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsProcReadOperationCount { get; set; }

    [Column("es_procReadTransferCount", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsProcReadTransferCount { get; set; }

    [Column("es_procThreadCount", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsProcThreadCount { get; set; }

    [Column("es_procUserModeTime", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsProcUserModeTime { get; set; }

    [Column("es_procVirtualSize", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsProcVirtualSize { get; set; }

    [Column("es_procWorkingSetSize", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsProcWorkingSetSize { get; set; }

    [Column("es_procWriteOperationCount", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsProcWriteOperationCount { get; set; }

    [Column("es_procWriteTransferCount", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsProcWriteTransferCount { get; set; }

    [Column("es_pcPrcAddressWidth", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsPcPrcAddressWidth { get; set; }

    [Column("es_pcPrcArchitecture", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsPcPrcArchitecture { get; set; }

    [Column("es_pcPrcAvailability", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsPcPrcAvailability { get; set; }

    [Column("es_pcPrcCaption", TypeName = "varchar(64)")]
    public string EsPcPrcCaption { get; set; }

    [Column("es_pcPrcCharacteristics", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcPrcCharacteristics { get; set; }

    [Column("es_pcPrcConfigManagerErrorCode", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcPrcConfigManagerErrorCode { get; set; }

    [Column("es_pcPrcConfigManagerUserConfig", TypeName = "NUMERIC(1, 0)")]
    public decimal? EsPcPrcConfigManagerUserConfig { get; set; }

    [Column("es_pcPrcCpuStatus", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsPcPrcCpuStatus { get; set; }

    [Column("es_pcPrcCurrentClockSpeed", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcPrcCurrentClockSpeed { get; set; }

    [Column("es_pcPrcCurrentVoltage", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsPcPrcCurrentVoltage { get; set; }

    [Column("es_pcPrcDataWidth", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsPcPrcDataWidth { get; set; }

    [Column("es_pcPrcExtClock", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcPrcExtClock { get; set; }

    [Column("es_pcPrcFamily", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsPcPrcFamily { get; set; }

    [Column("es_pcPrcL2CacheSize", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcPrcL2cacheSize { get; set; }

    [Column("es_pcPrcL2CacheSpeed", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcPrcL2cacheSpeed { get; set; }

    [Column("es_pcPrcL3CacheSize", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcPrcL3cacheSize { get; set; }

    [Column("es_pcPrcL3CacheSpeed", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcPrcL3cacheSpeed { get; set; }

    [Column("es_pcPrcLevel", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsPcPrcLevel { get; set; }

    [Column("es_pcPrcLoadPercentage", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsPcPrcLoadPercentage { get; set; }

    [Column("es_pcPrcMaxClockSpeed", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcPrcMaxClockSpeed { get; set; }

    [Column("es_pcPrcName", TypeName = "varchar(100)")]
    public string EsPcPrcName { get; set; }

    [Column("es_pcPrcNumberOfCores", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcPrcNumberOfCores { get; set; }

    [Column("es_pcPrcNumberOfEnabledCore", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcPrcNumberOfEnabledCore { get; set; }

    [Column("es_pcPrcNumberOfLogicalProcessors", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcPrcNumberOfLogicalProcessors { get; set; }

    [Column("es_pcPrcPowerManagementSupported", TypeName = "NUMERIC(1, 0)")]
    public decimal? EsPcPrcPowerManagementSupported { get; set; }

    [Column("es_pcPrcProcessorId", TypeName = "varchar(100)")]
    public string EsPcPrcProcessorId { get; set; }

    [Column("es_pcPrcProcessorType", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsPcPrcProcessorType { get; set; }

    [Column("es_pcPrcRevision", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsPcPrcRevision { get; set; }

    [Column("es_pcPrcSecondLevelAddressTranslationExtensions", TypeName = "NUMERIC(1, 0)")]
    public decimal? EsPcPrcSecondLevelAddressTranslationExtensions { get; set; }

    [Column("es_pcPrcStatus", TypeName = "varchar(10)")]
    public string EsPcPrcStatus { get; set; }

    [Column("es_pcPrcStatusInfo", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsPcPrcStatusInfo { get; set; }

    [Column("es_pcPrcSystemName", TypeName = "varchar(255)")]
    public string EsPcPrcSystemName { get; set; }

    [Column("es_pcPrcThreadCount", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsPcPrcThreadCount { get; set; }

    [Column("es_gpuAdapterRAM", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsGpuAdapterRam { get; set; }

    [Column("es_gpuAvailability", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsGpuAvailability { get; set; }

    [Column("es_gpuConfigManagerErrorCode", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsGpuConfigManagerErrorCode { get; set; }

    [Column("es_gpuCurrentBitsPerPixel", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsGpuCurrentBitsPerPixel { get; set; }

    [Column("es_gpuCurrentHorizontalResolution", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsGpuCurrentHorizontalResolution { get; set; }

    [Column("es_gpuCurrentNumberOfColors", TypeName = "NUMERIC(20, 0)")]
    public decimal? EsGpuCurrentNumberOfColors { get; set; }

    [Column("es_gpuCurrentRefreshRate", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsGpuCurrentRefreshRate { get; set; }

    [Column("es_gpuCurrentScanMode", TypeName = "NUMERIC(5, 0)")]
    public decimal? EsGpuCurrentScanMode { get; set; }

    [Column("es_gpuCurrentVerticalResolution", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsGpuCurrentVerticalResolution { get; set; }

    [Column("es_gpuDitherType", TypeName = "NUMERIC(10, 0)")]
    public decimal? EsGpuDitherType { get; set; }

    [Column("es_gpuDriverVersion", TypeName = "varchar(50)")]
    public string EsGpuDriverVersion { get; set; }

    [Column("es_gpuStatus", TypeName = "varchar(10)")]
    public string EsGpuStatus { get; set; }

    [Column("es_gpuVideoProcessor", TypeName = "varchar(100)")]
    public string EsGpuVideoProcessor { get; set; }

    [Column("fk_tb_matriz")]
    public int? FkTbMatriz { get; set; }

    [ForeignKey("FkTbMatriz")]
    [InverseProperty("TbEst")]
    public virtual TbMarcaProduto FkTbMatrizNavigation { get; set; }

    [InverseProperty("FkTbEstNavigation")]
    public virtual ICollection<TbHistorico> TbHistorico { get; set; } = new List<TbHistorico>();

    [InverseProperty("FkTbEstNavigation")]
    public virtual ICollection<TbJornada> TbJornada { get; set; } = new List<TbJornada>();

    [InverseProperty("FkTbEstNavigation")]
    public virtual ICollection<TbProduto> TbProduto { get; set; } = new List<TbProduto>();
}