// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_historico")]
[Index("FkTbAtor", Name = "ifk_tb_ator_tb_historico")]
[Index("FkTbEst", Name = "ifk_tb_est_tb_historico")]
public partial class TbHistorico
{
    [Key]
    [Column("id_historico")]
    public int IdHistorico { get; set; }

    [Column("hi_dtCri", TypeName = "DATETIME")]
    public DateTime HiDtCri { get; set; }

    [Column("hi_sqlTableName", TypeName = "VARCHAR(100)")]
    public string HiSqlTableName { get; set; }

    [Column("hi_sqlColumnName", TypeName = "VARCHAR(100)")]
    public string HiSqlColumnName { get; set; }

    [Column("hi_conteudoAnterior")]
    public string HiConteudoAnterior { get; set; }

    [Column("hi_conteudoNovo")]
    public string HiConteudoNovo { get; set; }

    [Column("fk_tb_est")]
    public int? FkTbEst { get; set; }

    [Column("fk_tb_ator")]
    public int? FkTbAtor { get; set; }

    [ForeignKey("FkTbAtor")]
    [InverseProperty("TbHistorico")]
    public virtual TbAtor FkTbAtorNavigation { get; set; }

    [ForeignKey("FkTbEst")]
    [InverseProperty("TbHistorico")]
    public virtual TbEst FkTbEstNavigation { get; set; }
}