// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_jornada")]
[Index("FkTbEst", Name = "ifk_tb_est_tb_jornada")]
[Index("FkTbPdv", Name = "ifk_tb_pdv_tb_jornada")]
public partial class TbJornada
{
    [Key]
    [Column("id_jornada")]
    public int IdJornada { get; set; }

    [Column("jo_dtCri", TypeName = "DATETIME")]
    public DateTime JoDtCri { get; set; }

    [Column("jo_dtAlt", TypeName = "DATETIME")]
    public DateTime JoDtAlt { get; set; }

    [Column("jo_dtAcs", TypeName = "DATETIME")]
    public DateTime? JoDtAcs { get; set; }

    [Column("jo_desat", TypeName = "NUMERIC(1, 0)")]
    public int? JoDesat { get; set; }

    [Column("jo_numSeq", TypeName = "bigint")]
    public long JoNumSeq { get; set; }

    [Column("jo_aberta", TypeName = "NUMERIC(1, 0)")]
    public int? JoAberta { get; set; }

    [Column("jo_canc", TypeName = "NUMERIC(1, 0)")]
    public int? JoCanc { get; set; }

    [Column("fk_tb_pdv")]
    public int? FkTbPdv { get; set; }

    [Column("fk_tb_est")]
    public int? FkTbEst { get; set; }

    [ForeignKey("FkTbEst")]
    [InverseProperty("TbJornada")]
    public virtual TbEst FkTbEstNavigation { get; set; }

    [ForeignKey("FkTbPdv")]
    [InverseProperty("TbJornada")]
    public virtual TbPdv FkTbPdvNavigation { get; set; }

    [InverseProperty("FkTbJornadaNavigation")]
    public virtual ICollection<TbMovimentacao> TbMovimentacao { get; set; } = new List<TbMovimentacao>();
}