// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_movimentacao_pagamento_parcela")]
[Index("FkTbMovimentacaoPagamento", Name = "ifk_tb_movimentacao_pagamento_tb_movimentacao_pagamento_parcela")]
[Index("FkTbSubFormaPagamento", Name = "ifk_tb_sub_forma_pagamento_tb_movimentacao_pagamento_parcela")]
public partial class TbMovimentacaoPagamentoParcela
{
    [Key]
    [Column("id_movimentacao_pagamento_parcela")]
    public int IdMovimentacaoPagamentoParcela { get; set; }

    [Column("mpp_dtCri", TypeName = "DATETIME")]
    public DateTime MppDtCri { get; set; }

    [Column("mpp_dtAlt", TypeName = "DATETIME")]
    public DateTime MppDtAlt { get; set; }

    [Column("mpp_dtAcs", TypeName = "DATETIME")]
    public DateTime? MppDtAcs { get; set; }

    [Column("mpp_numParc", TypeName = "smallint")]
    public short MppNumParc { get; set; }

    [Column("mpp_qtdParc", TypeName = "smallint")]
    public short MppQtdParc { get; set; }

    [Column("mpp_vlrCli", TypeName = "NUMERIC(13, 2)")]
    public decimal? MppVlrCli { get; set; }

    [Column("mpp_taxaParc", TypeName = "NUMERIC(6, 3)")]
    public decimal? MppTaxaParc { get; set; }

    [Column("mpp_vlrRec", TypeName = "NUMERIC(13, 2)")]
    public decimal? MppVlrRec { get; set; }

    [Column("mpp_dtVenc", TypeName = "DATETIME")]
    public DateTime MppDtVenc { get; set; }

    [Column("mpp_canc", TypeName = "NUMERIC(1, 0)")]
    public decimal? MppCanc { get; set; }

    [Column("fk_tb_movimentacao_pagamento")]
    public int? FkTbMovimentacaoPagamento { get; set; }

    [Column("fk_tb_sub_forma_pagamento")]
    public int? FkTbSubFormaPagamento { get; set; }

    [ForeignKey("FkTbMovimentacaoPagamento")]
    [InverseProperty("TbMovimentacaoPagamentoParcela")]
    public virtual TbMovimentacaoPagamento FkTbMovimentacaoPagamentoNavigation { get; set; }

    [ForeignKey("FkTbSubFormaPagamento")]
    [InverseProperty("TbMovimentacaoPagamentoParcela")]
    public virtual TbSubFormaPagamento FkTbSubFormaPagamentoNavigation { get; set; }
}