// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_movimentacao_caixa")]
[Index("FkTbMovimentacao", Name = "ifk_tb_movimentacao_tb_movimentacao_caixa")]
public partial class TbMovimentacaoCaixa
{
    [Key]
    [Column("id_movimentacao_caixa")]
    public int IdMovimentacaoCaixa { get; set; }

    [Column("mc_canc", TypeName = "NUMERIC(1, 0)")]
    public decimal? McCanc { get; set; }

    [Column("fk_tb_movimentacao")]
    public int? FkTbMovimentacao { get; set; }

    [ForeignKey("FkTbMovimentacao")]
    [InverseProperty("TbMovimentacaoCaixa")]
    public virtual TbMovimentacao FkTbMovimentacaoNavigation { get; set; }
}