// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_movimentacao")]
[Index("FkTbAtorAtend", Name = "ifk_tb_ator_atend_tb_movimentacao")]
[Index("FkTbAtorDest", Name = "ifk_tb_ator_dest_tb_movimentacao")]
[Index("FkTbAtorEmit", Name = "ifk_tb_ator_emit_tb_movimentacao")]
[Index("FkTbClasCont2", Name = "ifk_tb_clasCont2_tb_movimentacao")]
[Index("FkTbJornada", Name = "ifk_tb_jornada_tb_movimentacao")]
public partial class TbMovimentacao
{
    [Key]
    [Column("id_movimentacao")]
    public int IdMovimentacao { get; set; }

    [Column("mv_nfeTipoAmb", TypeName = "tinyint")]
    public byte MvNfeTipoAmb { get; set; }

    [Column("mv_dtCri", TypeName = "DATETIME")]
    public DateTime MvDtCri { get; set; }

    [Column("mv_dtAlt", TypeName = "DATETIME")]
    public DateTime MvDtAlt { get; set; }

    [Column("mv_dtAcs", TypeName = "DATETIME")]
    public DateTime? MvDtAcs { get; set; }

    [Column("mv_qtdItens", TypeName = "bigint")]
    public long MvQtdItens { get; set; }

    [Column("mv_numSeq", TypeName = "bigint")]
    public long MvNumSeq { get; set; }

    [Column("mv_canc", TypeName = "NUMERIC(1, 0)")]
    public int? MvCanc { get; set; }

    [Column("mv_conc", TypeName = "NUMERIC(1, 0)")]
    public int? MvConc { get; set; }

    [Column("mv_quit", TypeName = "NUMERIC(1, 0)")]
    public int? MvQuit { get; set; }

    [Column("mv_movTipo", TypeName = "smallint")]
    public short MvMovTipo { get; set; }

    [Column("mv_codSeqAbertFechCx", TypeName = "bigint")]
    public long MvCodSeqAbertFechCx { get; set; }

    [Column("mv_movAbertCx")]
    public int? MvMovAbertCx { get; set; }

    [Column("mv_cxAberto", TypeName = "NUMERIC(1, 0)")]
    public int? MvCxAberto { get; set; }

    [Column("mv_nfeEnfilGer", TypeName = "NUMERIC(1, 0)")]
    public int? MvNfeEnfilGer { get; set; }

    [Column("mv_nfeNatOp", TypeName = "varchar(60)")]
    public string MvNfeNatOp { get; set; }

    [Column("mv_nfeVlrTotProd", TypeName = "NUMERIC(13, 2)")]
    public int? MvNfeVlrTotProd { get; set; }

    [Column("mv_nfeVlrTotNF", TypeName = "NUMERIC(13, 2)")]
    public int? MvNfeVlrTotNf { get; set; }

    [Column("mv_nfeVlrTotDesc", TypeName = "NUMERIC(13, 2)")]
    public double? MvNfeVlrTotDesc { get; set; }

    [Column("mv_nfeVlrIcmsDeson", TypeName = "NUMERIC(13, 2)")]
    public int? MvNfeVlrIcmsDeson { get; set; }

    [Column("mv_nfeVlrTotIcmsSt", TypeName = "NUMERIC(13, 2)")]
    public int? MvNfeVlrTotIcmsSt { get; set; }

    [Column("mv_nfeVlrTotFcpRetSt", TypeName = "NUMERIC(13, 2)")]
    public int? MvNfeVlrTotFcpRetSt { get; set; }

    [Column("mv_nfeVlrTotFrete", TypeName = "NUMERIC(13, 2)")]
    public int? MvNfeVlrTotFrete { get; set; }

    [Column("mv_nfeVlrTotSeg", TypeName = "NUMERIC(13, 2)")]
    public int? MvNfeVlrTotSeg { get; set; }

    [Column("mv_nfeVlrTotOutro", TypeName = "NUMERIC(13, 2)")]
    public int? MvNfeVlrTotOutro { get; set; }

    [Column("mv_nfeVlrTotImpImp", TypeName = "NUMERIC(13, 2)")]
    public int? MvNfeVlrTotImpImp { get; set; }

    [Column("mv_nfeVlrTotIpi", TypeName = "NUMERIC(13, 2)")]
    public int? MvNfeVlrTotIpi { get; set; }

    [Column("mv_nfeVlrTotIpiDevol", TypeName = "NUMERIC(13, 2)")]
    public int? MvNfeVlrTotIpiDevol { get; set; }

    [Column("mv_nfeVlrTroco", TypeName = "NUMERIC(13, 2)")]
    public double? MvNfeVlrTroco { get; set; }

    [Column("mv_nfeBcIcms", TypeName = "NUMERIC(13, 2)")]
    public int? MvNfeBcIcms { get; set; }

    [Column("mv_nfeVlrBcIcmsSt", TypeName = "NUMERIC(13, 2)")]
    public int? MvNfeVlrBcIcmsSt { get; set; }

    [Column("mv_nfeVlrTotTrib", TypeName = "NUMERIC(13, 2)")]
    public int? MvNfeVlrTotTrib { get; set; }

    [Column("mv_nfeChave", TypeName = "varchar(50)")]
    public string MvNfeChave { get; set; }

    [Column("mv_nfeVlrTotCofins", TypeName = "NUMERIC(13, 2)")]
    public int? MvNfeVlrTotCofins { get; set; }

    [Column("mv_nfeVlrTotFcp", TypeName = "NUMERIC(13, 2)")]
    public int? MvNfeVlrTotFcp { get; set; }

    [Column("mv_nfeVlrTotFcpSt", TypeName = "NUMERIC(13, 2)")]
    public int? MvNfeVlrTotFcpSt { get; set; }

    [Column("mv_nfeVlrTotIcms", TypeName = "NUMERIC(13, 2)")]
    public int? MvNfeVlrTotIcms { get; set; }

    [Column("mv_nfeVlrTotPis", TypeName = "NUMERIC(13, 2)")]
    public double? MvNfeVlrTotPis { get; set; }

    [Column("mv_nfeIdentLocDestOp", TypeName = "tinyint")]
    public byte MvNfeIdentLocDestOp { get; set; }

    [Column("mv_nfeMod", TypeName = "tinyint")]
    public byte MvNfeMod { get; set; }

    [Column("mv_nfeIndOpConsumFin", TypeName = "tinyint")]
    public byte MvNfeIndOpConsumFin { get; set; }

    [Column("mv_nfeFinEmis", TypeName = "tinyint")]
    public byte MvNfeFinEmis { get; set; }

    [Column("mv_nfeIndInterm", TypeName = "INT")]
    public int MvNfeIndInterm { get; set; }

    [Column("mv_nfeIndPresCompEstMomOp", TypeName = "tinyint")]
    public byte MvNfeIndPresCompEstMomOp { get; set; }

    [Column("mv_nfeTipo", TypeName = "tinyint")]
    public byte MvNfeTipo { get; set; }

    [Column("mv_nfeTipoImpDanfe", TypeName = "tinyint")]
    public byte MvNfeTipoImpDanfe { get; set; }

    [Column("mv_nfeCfop", TypeName = "varchar(3)")]
    public string MvNfeCfop { get; set; }

    [Column("mv_nfeProcEmis", TypeName = "tinyint")]
    public byte MvNfeProcEmis { get; set; }

    [Column("mv_nfeVerProcEmis", TypeName = "varchar(20)")]
    public string MvNfeVerProcEmis { get; set; }

    [Column("mv_nfeModFrete", TypeName = "tinyint")]
    public byte MvNfeModFrete { get; set; }

    [Column("mv_nfeDtEmis", TypeName = "DATETIME")]
    public DateTime? MvNfeDtEmis { get; set; }

    [Column("mv_nfeTipoEmis", TypeName = "tinyint")]
    public byte MvNfeTipoEmis { get; set; }

    [Column("mv_nfeTipoDfe", TypeName = "tinyint")]
    public byte MvNfeTipoDfe { get; set; }

    [Column("mv_nfeXmlProcRes")]
    public string MvNfeXmlProcRes { get; set; }

    [Column("mv_vlrTotPag", TypeName = "NUMERIC(13, 2)")]
    public int? MvVlrTotPag { get; set; }

    [Column("mv_cpf_tmp", TypeName = "varchar(11)")]
    public string MvCpfTmp { get; set; }

    [Column("fk_tb_clasCont2")]
    public int? FkTbClasCont2 { get; set; }

    [Column("fk_tb_jornada")]
    public int? FkTbJornada { get; set; }

    [Column("fk_tb_ator_atend")]
    public int? FkTbAtorAtend { get; set; }

    [Column("fk_tb_ator_dest")]
    public int? FkTbAtorDest { get; set; }

    [Column("fk_tb_ator_emit")]
    public int? FkTbAtorEmit { get; set; }

    [ForeignKey("FkTbAtorAtend")]
    [InverseProperty("TbMovimentacaoFkTbAtorAtendNavigation")]
    public virtual TbAtor FkTbAtorAtendNavigation { get; set; }

    [ForeignKey("FkTbAtorDest")]
    [InverseProperty("TbMovimentacaoFkTbAtorDestNavigation")]
    public virtual TbAtor FkTbAtorDestNavigation { get; set; }

    [ForeignKey("FkTbAtorEmit")]
    [InverseProperty("TbMovimentacaoFkTbAtorEmitNavigation")]
    public virtual TbAtor FkTbAtorEmitNavigation { get; set; }

    [ForeignKey("FkTbClasCont2")]
    [InverseProperty("TbMovimentacao")]
    public virtual TbClasCont2 FkTbClasCont2Navigation { get; set; }

    [ForeignKey("FkTbJornada")]
    [InverseProperty("TbMovimentacao")]
    public virtual TbJornada FkTbJornadaNavigation { get; set; }

    [InverseProperty("FkTbMovimentacaoNavigation")]
    public virtual ICollection<TbMovimentacaoCaixa> TbMovimentacaoCaixa { get; set; } = new List<TbMovimentacaoCaixa>();

    [InverseProperty("FkTbMovimentacaoNavigation")]
    public virtual ICollection<TbMovimentacaoImpressao> TbMovimentacaoImpressao { get; set; } = new List<TbMovimentacaoImpressao>();

    [InverseProperty("FkTbMovimentacaoNavigation")]
    public virtual ICollection<TbMovimentacaoPagamento> TbMovimentacaoPagamento { get; set; } = new List<TbMovimentacaoPagamento>();

    [InverseProperty("FkTbMovimentacaoNavigation")]
    public virtual ICollection<TbMovimentacaoProduto> TbMovimentacaoProduto { get; set; } = new List<TbMovimentacaoProduto>();

    [InverseProperty("FkTbMovimentacaoNavigation")]
    public virtual ICollection<TbNfe> TbNfe { get; set; } = new List<TbNfe>();
}