// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_municipio")]
[Index("FkTbEstadosBr", Name = "ifk_tb_estados_br_tb_municipio")]
public partial class TbMunicipio
{
    [Key]
    [Column("id_municipio")]
    public int IdMunicipio { get; set; }

    [Column("mu_desat", TypeName = "NUMERIC(1, 0)")]
    public int? MuDesat { get; set; }

    [Column("mu_id", TypeName = "INT")]
    public int? MuId { get; set; }

    [Column("mu_nome", TypeName = "varchar(40)")]
    public string MuNome { get; set; }

    [Column("fk_tb_estados_br")]
    public int? FkTbEstadosBr { get; set; }

    [ForeignKey("FkTbEstadosBr")]
    [InverseProperty("TbMunicipio")]
    public virtual TbEstadosBr FkTbEstadosBrNavigation { get; set; }

    [InverseProperty("FkTbMunicipioNavigation")]
    public virtual ICollection<TbAtor> TbAtor { get; set; } = new List<TbAtor>();
}