// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_ncm")]
public partial class TbNcm
{
    [Key]
    [Column("id_ncm")]
    public int IdNcm { get; set; }

    [Column("nc_dtCri", TypeName = "DATETIME")]
    public DateTime NcDtCri { get; set; }

    [Column("nc_dtAlt", TypeName = "DATETIME")]
    public DateTime NcDtAlt { get; set; }

    [Column("nc_dtAcs", TypeName = "DATETIME")]
    public DateTime? NcDtAcs { get; set; }

    [Column("nc_desat", TypeName = "NUMERIC(1, 0)")]
    public decimal? NcDesat { get; set; }

    [Column("nc_anoDoAto", TypeName = "varchar(10)")]
    public string NcAnoDoAto { get; set; }

    [Column("nc_numAto", TypeName = "INT")]
    public int NcNumAto { get; set; }

    [Column("nc_parentOid")]
    public int? NcParentOid { get; set; }

    [Column("nc_rootNcm", TypeName = "varchar(2)")]
    public string NcRootNcm { get; set; }

    [Column("nc_ncmBase", TypeName = "varchar(8)")]
    public string NcNcmBase { get; set; }

    [Column("nc_ncmFull", TypeName = "varchar(8)")]
    public string NcNcmFull { get; set; }

    [Column("nc_desc", TypeName = "varchar(2048)")]
    public string NcDesc { get; set; }

    [Column("nc_dtIni", TypeName = "DATETIME")]
    public DateTime NcDtIni { get; set; }

    [Column("nc_dtFim", TypeName = "DATETIME")]
    public DateTime NcDtFim { get; set; }

    [InverseProperty("FkTbNcmNavigation")]
    public virtual ICollection<TbProduto> TbProduto { get; set; } = new List<TbProduto>();

    [InverseProperty("FkTbNcmNavigation")]
    public virtual ICollection<TbSubcategoriaProduto> TbSubcategoriaProduto { get; set; } = new List<TbSubcategoriaProduto>();
}