// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_pais")]
[Index("FkTbUnidadeMonetaria", Name = "ifk_tb_unidade_monetaria_tb_pais")]
public partial class TbPais
{
    [Key]
    [Column("id_pais")]
    public int IdPais { get; set; }

    [Column("ps_desat", TypeName = "NUMERIC(1, 0)")]
    public int? PsDesat { get; set; }

    [Column("ps_id", TypeName = "smallint")]
    public short? PsId { get; set; }

    [Column("ps_sigla", TypeName = "varchar(3)")]
    public string PsSigla { get; set; }

    [Column("ps_nome", TypeName = "varchar(256)")]
    public string PsNome { get; set; }

    [Column("ps_canc", TypeName = "NUMERIC(1, 0)")]
    public int? PsCanc { get; set; }

    [Column("fk_tb_unidade_monetaria")]
    public int? FkTbUnidadeMonetaria { get; set; }

    [ForeignKey("FkTbUnidadeMonetaria")]
    [InverseProperty("TbPais")]
    public virtual TbUnidadeMonetaria FkTbUnidadeMonetariaNavigation { get; set; }

    [InverseProperty("FkTbPaisNavigation")]
    public virtual ICollection<TbRegioesBr> TbRegioesBr { get; set; } = new List<TbRegioesBr>();
}