// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_planCont")]
public partial class TbPlanCont
{
    [Key]
    [Column("id_planCont")]
    public int IdPlanCont { get; set; }

    [Column("pc_desc", TypeName = "varchar(60)")]
    public string PcDesc { get; set; }

    [Column("pc_dtCri", TypeName = "DATETIME")]
    public DateTime PcDtCri { get; set; }

    [Column("pc_dtAlt", TypeName = "DATETIME")]
    public DateTime PcDtAlt { get; set; }

    [Column("pc_dtAcs", TypeName = "DATETIME")]
    public DateTime? PcDtAcs { get; set; }

    [Column("pc_desat", TypeName = "NUMERIC(1, 0)")]
    public decimal? PcDesat { get; set; }

    [Column("pc_canc", TypeName = "NUMERIC(1, 0)")]
    public decimal? PcCanc { get; set; }
}