// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_rede")]
public partial class TbRede
{
    [Key]
    [Column("id_rede")]
    public int IdRede { get; set; }

    [Column("re_dtCri", TypeName = "DATETIME")]
    public DateTime ReDtCri { get; set; }

    [Column("re_dtAlt", TypeName = "DATETIME")]
    public DateTime ReDtAlt { get; set; }

    [Column("re_dtAcs", TypeName = "DATETIME")]
    public DateTime? ReDtAcs { get; set; }

    [Column("re_desc", TypeName = "varchar(60)")]
    public string ReDesc { get; set; }

    [Column("re_desat", TypeName = "NUMERIC(1, 0)")]
    public int? ReDesat { get; set; }

    [Column("re_desatSinc", TypeName = "NUMERIC(1, 0)")]
    public int? ReDesatSinc { get; set; }

    [Column("re_PersTim", TypeName = "tinyint")]
    public byte RePersTim { get; set; }

    [InverseProperty("FkTbRedeNavigation")]
    public virtual ICollection<TbClasCont1> TbClasCont1 { get; set; } = new List<TbClasCont1>();

    [InverseProperty("FkTbRedeNavigation")]
    public virtual ICollection<TbFormaPagamento> TbFormaPagamento { get; set; } = new List<TbFormaPagamento>();

    [InverseProperty("FkTbRedeNavigation")]
    public virtual ICollection<TbMarcaProduto> TbMarcaProduto { get; set; } = new List<TbMarcaProduto>();

    [InverseProperty("FkTbRedeNavigation")]
    public virtual ICollection<TbMatriz> TbMatriz { get; set; } = new List<TbMatriz>();

    [InverseProperty("FkTbRedeNavigation")]
    public virtual ICollection<TbProduto> TbProduto { get; set; } = new List<TbProduto>();

    [InverseProperty("FkTbRedeNavigation")]
    public virtual ICollection<TbSecaoProduto> TbSecaoProduto { get; set; } = new List<TbSecaoProduto>();
}