// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_relacao_produto_cadastro_XML")]
[Index("FkTbAtor", Name = "ifk_tb_ator_tb_relacao_produto_cadastro_XML")]
[Index("FkTbProdutoFilial", Name = "ifk_tb_produto_filial_tb_relacao_produto_cadastro_XML")]
[Index("FkTbProduto", Name = "ifk_tb_produto_tb_relacao_produto_cadastro_XML")]
public partial class TbRelacaoProdutoCadastroXml
{
    [Key]
    [Column("id_relacao_produto_cadastro_XML")]
    public int IdRelacaoProdutoCadastroXml { get; set; }

    [Column("rpc_codRef", TypeName = "bigint")]
    public long RpcCodRef { get; set; }

    [Column("rpc_desc", TypeName = "varchar(48)")]
    public string RpcDesc { get; set; }

    [Column("rpc_cnpj_fornecedor", TypeName = "varchar(18)")]
    public string RpcCnpjFornecedor { get; set; }

    [Column("rpc_dtCri", TypeName = "DATETIME")]
    public DateTime RpcDtCri { get; set; }

    [Column("rpc_dtAlt", TypeName = "DATETIME")]
    public DateTime RpcDtAlt { get; set; }

    [Column("rpc_dtAcs", TypeName = "DATETIME")]
    public DateTime? RpcDtAcs { get; set; }

    [Column("fk_tb_produto")]
    public int? FkTbProduto { get; set; }

    [Column("fk_tb_produto_filial")]
    public int? FkTbProdutoFilial { get; set; }

    [Column("fk_tb_ator")]
    public int? FkTbAtor { get; set; }

    [ForeignKey("FkTbAtor")]
    [InverseProperty("TbRelacaoProdutoCadastroXml")]
    public virtual TbAtor FkTbAtorNavigation { get; set; }

    [ForeignKey("FkTbProdutoFilial")]
    [InverseProperty("TbRelacaoProdutoCadastroXml")]
    public virtual TbProdutoFilial FkTbProdutoFilialNavigation { get; set; }

    [ForeignKey("FkTbProduto")]
    [InverseProperty("TbRelacaoProdutoCadastroXml")]
    public virtual TbProduto FkTbProdutoNavigation { get; set; }

    [InverseProperty("FkTbRelacaoProdutoCadastroXmlNavigation")]
    public virtual ICollection<TbProduto> TbProduto { get; set; } = new List<TbProduto>();
}