// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_subcategoria_produto")]
[Index("FkTbNcm", Name = "ifk_tb_Ncm_tb_subcategoria_produto")]
[Index("FkTbCategoriaProduto", Name = "ifk_tb_categoria_produto_tb_subcategoria_produto")]
public partial class TbSubcategoriaProduto
{
    [Key]
    [Column("id_subcategoria_produto")]
    public int IdSubcategoriaProduto { get; set; }

    [Column("scp_nfePisCofinsReg", TypeName = "tinyint")]
    public byte ScpNfePisCofinsReg { get; set; }

    [Column("scp_dtCri", TypeName = "DATETIME")]
    public DateTime ScpDtCri { get; set; }

    [Column("scp_dtAlt", TypeName = "DATETIME")]
    public DateTime ScpDtAlt { get; set; }

    [Column("scp_dtAcs", TypeName = "DATETIME")]
    public DateTime? ScpDtAcs { get; set; }

    [Column("scp_desc", TypeName = "varchar(48)")]
    public string ScpDesc { get; set; }

    [Column("scp_desat", TypeName = "NUMERIC(1, 0)")]
    public int? ScpDesat { get; set; }

    [Column("scp_ncmNum", TypeName = "varchar(8)")]
    public string ScpNcmNum { get; set; }

    [Column("scp_nfeCsosn", TypeName = "smallint")]
    public short ScpNfeCsosn { get; set; }

    [Column("scp_descMax", TypeName = "NUMERIC(13, 2)")]
    public int? ScpDescMax { get; set; }

    [Column("fk_tb_categoria_produto")]
    public int? FkTbCategoriaProduto { get; set; }

    [Column("fk_tb_Ncm")]
    public int? FkTbNcm { get; set; }

    [ForeignKey("FkTbCategoriaProduto")]
    [InverseProperty("TbSubcategoriaProduto")]
    public virtual TbCategoriaProduto FkTbCategoriaProdutoNavigation { get; set; }

    [ForeignKey("FkTbNcm")]
    [InverseProperty("TbSubcategoriaProduto")]
    public virtual TbNcm FkTbNcmNavigation { get; set; }

    [InverseProperty("FkTbSubcategoriaProdutoNavigation")]
    public virtual ICollection<TbProduto> TbProduto { get; set; } = new List<TbProduto>();
}