// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_unidade_monetaria")]
public partial class TbUnidadeMonetaria
{
    [Key]
    [Column("id_unidade_monetaria")]
    public int IdUnidadeMonetaria { get; set; }

    [Column("un_id", TypeName = "smallint")]
    public short? UnId { get; set; }

    [Column("un_sigla", TypeName = "varchar(3)")]
    public string UnSigla { get; set; }

    [Column("un_nome", TypeName = "varchar(256)")]
    public string UnNome { get; set; }

    [Column("un_inter", TypeName = "NUMERIC(1, 0)")]
    public int? UnInter { get; set; }

    [Column("un_cambio", TypeName = "NUMERIC(13, 2)")]
    public int? UnCambio { get; set; }

    [Column("un_cambioDt")]
    public double? UnCambioDt { get; set; }

    [Column("un_canc", TypeName = "NUMERIC(1, 0)")]
    public int? UnCanc { get; set; }

    [InverseProperty("FkTbUnidadeMonetariaNavigation")]
    public virtual ICollection<TbPais> TbPais { get; set; } = new List<TbPais>();
}