// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_certificado_digital")]
[Index("FkTbAtor", Name = "ifk_tb_ator_tb_certificado_digital")]
public partial class TbCertificadoDigital
{
    [Key]
    [Column("id_certificado_digital")]
    public int IdCertificadoDigital { get; set; }

    [Column("cd_dtCri", TypeName = "DATETIME")]
    public DateTime CdDtCri { get; set; }

    [Column("cd_dtAlt", TypeName = "DATETIME")]
    public DateTime CdDtAlt { get; set; }

    [Column("cd_dtAcs", TypeName = "DATETIME")]
    public DateTime? CdDtAcs { get; set; }

    [Column("cd_cnpj", TypeName = "varchar(18)")]
    public string CdCnpj { get; set; }

    [Column("cd_razSoc", TypeName = "varchar(60)")]
    public string CdRazSoc { get; set; }

    [Column("cd_rawData")]
    public byte[] CdRawData { get; set; }

    [Column("cd_pwd", TypeName = "varchar(64)")]
    public string CdPwd { get; set; }

    [Column("cd_serial", TypeName = "varchar(128)")]
    public string CdSerial { get; set; }

    [Column("cd_dtPub", TypeName = "DATETIME")]
    public DateTime? CdDtPub { get; set; }

    [Column("cd_dtExp", TypeName = "DATETIME")]
    public DateTime? CdDtExp { get; set; }

    [Column("cd_ativo", TypeName = "NUMERIC(1, 0)")]
    public int? CdAtivo { get; set; }

    [Column("cd_tipo", TypeName = "varchar(50)")]
    public string CdTipo { get; set; }

    [Column("cd_modoEmissao", TypeName = "varchar(50)")]
    public string CdModoEmissao { get; set; }

    [Column("cd_x509Version", TypeName = "INT")]
    public int CdX509Version { get; set; }

    [Column("cd_sHA1String", TypeName = "varchar(128)")]
    public string CdSHa1string { get; set; }

    [Column("cd_canc", TypeName = "NUMERIC(1, 0)")]
    public int? CdCanc { get; set; }

    [Column("fk_tb_ator")]
    public int? FkTbAtor { get; set; }

    [ForeignKey("FkTbAtor")]
    [InverseProperty("TbCertificadoDigital")]
    public virtual TbAtor FkTbAtorNavigation { get; set; }

    [InverseProperty("FkTbCertificadoDigitalNavigation")]
    public virtual ICollection<TbAtor> TbAtor { get; set; } = new List<TbAtor>();
}