// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_clasCont1")]
[Index("FkTbRede", Name = "ifk_tb_rede_tb_clasCont1")]
public partial class TbClasCont1
{
    [Key]
    [Column("id_clasCont1")]
    public int IdClasCont1 { get; set; }

    [Column("cc1_dtCri", TypeName = "DATETIME")]
    public DateTime Cc1DtCri { get; set; }

    [Column("cc1_dtAlt", TypeName = "DATETIME")]
    public DateTime Cc1DtAlt { get; set; }

    [Column("cc1_dtAcs", TypeName = "DATETIME")]
    public DateTime? Cc1DtAcs { get; set; }

    [Column("cc1_desat", TypeName = "NUMERIC(1, 0)")]
    public decimal? Cc1Desat { get; set; }

    [Column("cc1_desc", TypeName = "varchar(48)")]
    public string Cc1Desc { get; set; }

    [Column("cc1_saida", TypeName = "NUMERIC(1, 0)")]
    public decimal? Cc1Saida { get; set; }

    [Column("fk_tb_rede")]
    public int? FkTbRede { get; set; }

    [ForeignKey("FkTbRede")]
    [InverseProperty("TbClasCont1")]
    public virtual TbRede FkTbRedeNavigation { get; set; }
}