// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_contExtSec")]
public partial class TbContExtSec
{
    [Key]
    [Column("id_contExtSec")]
    public int IdContExtSec { get; set; }

    [Column("ces_deb", TypeName = "NUMERIC(13, 2)")]
    public decimal? CesDeb { get; set; }

    [Column("ces_cred", TypeName = "NUMERIC(13, 2)")]
    public decimal? CesCred { get; set; }

    [Column("ces_dtCri", TypeName = "DATETIME")]
    public DateTime CesDtCri { get; set; }

    [Column("ces_dtAlt", TypeName = "DATETIME")]
    public DateTime CesDtAlt { get; set; }

    [Column("ces_dtAcs", TypeName = "DATETIME")]
    public DateTime? CesDtAcs { get; set; }

    [Column("ces_canc", TypeName = "NUMERIC(1, 0)")]
    public decimal? CesCanc { get; set; }

    [Column("ces_conc", TypeName = "NUMERIC(1, 0)")]
    public decimal? CesConc { get; set; }

    [Column("fk_tb_contSec")]
    public int? FkTbContSec { get; set; }

    [ForeignKey("FkTbContSec")]
    [InverseProperty("TbContExtSec")]
    public virtual TbContSec FkTbContSecNavigation { get; set; }
}