// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_contSec")]
public partial class TbContSec
{
    [Key]
    [Column("id_contSec")]
    public int IdContSec { get; set; }

    [Column("cs_dtCri", TypeName = "DATETIME")]
    public DateTime CsDtCri { get; set; }

    [Column("cs_dtAlt", TypeName = "DATETIME")]
    public DateTime CsDtAlt { get; set; }

    [Column("cs_dtAcs", TypeName = "DATETIME")]
    public DateTime? CsDtAcs { get; set; }

    [Column("cs_desc", TypeName = "varchar(60)")]
    public string CsDesc { get; set; }

    [Column("cs_canc", TypeName = "NUMERIC(1, 0)")]
    public decimal? CsCanc { get; set; }

    [Column("cs_conc", TypeName = "NUMERIC(1, 0)")]
    public decimal? CsConc { get; set; }

    [InverseProperty("FkTbContSecNavigation")]
    public virtual ICollection<TbContExtSec> TbContExtSec { get; set; } = new List<TbContExtSec>();
}