// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_contExtGru")]
[Index("FkTbContGru", Name = "ifk_tb_contGru_tb_contExtGru")]
public partial class TbContExtGru
{
    [Key]
    [Column("id_contExtGru")]
    public int IdContExtGru { get; set; }

    [Column("ceg_deb", TypeName = "NUMERIC(13, 2)")]
    public decimal? CegDeb { get; set; }

    [Column("ceg_cred", TypeName = "NUMERIC(13, 2)")]
    public decimal? CegCred { get; set; }

    [Column("ceg_dtCri", TypeName = "DATETIME")]
    public DateTime CegDtCri { get; set; }

    [Column("ceg_dtAlt", TypeName = "DATETIME")]
    public DateTime CegDtAlt { get; set; }

    [Column("ceg_dtAcs", TypeName = "DATETIME")]
    public DateTime? CegDtAcs { get; set; }

    [Column("ceg_canc", TypeName = "NUMERIC(1, 0)")]
    public decimal? CegCanc { get; set; }

    [Column("ceg_conc", TypeName = "NUMERIC(1, 0)")]
    public decimal? CegConc { get; set; }

    [Column("fk_tb_contGru")]
    public int? FkTbContGru { get; set; }

    [ForeignKey("FkTbContGru")]
    [InverseProperty("TbContExtGru")]
    public virtual TbContGru FkTbContGruNavigation { get; set; }
}