// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_contExt")]
[Index("FkTbCont", Name = "ifk_tb_cont_tb_contExt")]
public partial class TbContExt
{
    [Key]
    [Column("id_contExt")]
    public int IdContExt { get; set; }

    [Column("ce_deb", TypeName = "NUMERIC(13, 2)")]
    public decimal? CeDeb { get; set; }

    [Column("ce_cred", TypeName = "NUMERIC(13, 2)")]
    public decimal? CeCred { get; set; }

    [Column("ce_dtCri", TypeName = "DATETIME")]
    public DateTime CeDtCri { get; set; }

    [Column("ce_dtAlt", TypeName = "DATETIME")]
    public DateTime CeDtAlt { get; set; }

    [Column("ce_dtAcs", TypeName = "DATETIME")]
    public DateTime? CeDtAcs { get; set; }

    [Column("ce_canc", TypeName = "NUMERIC(1, 0)")]
    public decimal? CeCanc { get; set; }

    [Column("ce_conc", TypeName = "NUMERIC(1, 0)")]
    public decimal? CeConc { get; set; }

    [Column("fk_tb_cont")]
    public int? FkTbCont { get; set; }

    [ForeignKey("FkTbCont")]
    [InverseProperty("TbContExt")]
    public virtual TbCont FkTbContNavigation { get; set; }
}