// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_estados_br")]
[Index("FkTbRegioesBr", Name = "ifk_tb_regioes_br_tb_estados_br")]
public partial class TbEstadosBr
{
    [Key]
    [Column("id_estados_br")]
    public int IdEstadosBr { get; set; }

    [Column("eb_desat", TypeName = "NUMERIC(1, 0)")]
    public int? EbDesat { get; set; }

    [Column("eb_id", TypeName = "tinyint")]
    public byte? EbId { get; set; }

    [Column("eb_sigla", TypeName = "varchar(2)")]
    public string EbSigla { get; set; }

    [Column("eb_nome", TypeName = "varchar(20)")]
    public string EbNome { get; set; }

    [Column("fk_tb_regioes_br")]
    public int? FkTbRegioesBr { get; set; }

    [ForeignKey("FkTbRegioesBr")]
    [InverseProperty("TbEstadosBr")]
    public virtual TbRegioesBr FkTbRegioesBrNavigation { get; set; }

    [InverseProperty("FkTbEstadosBrNavigation")]
    public virtual ICollection<TbAtor> TbAtor { get; set; } = new List<TbAtor>();

    [InverseProperty("FkTbEstadosBrNavigation")]
    public virtual ICollection<TbMunicipio> TbMunicipio { get; set; } = new List<TbMunicipio>();
}