// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_forma_pagamento")]
[Index("FkTbRede", Name = "ifk_tb_rede_tb_forma_pagamento")]
public partial class TbFormaPagamento
{
    [Key]
    [Column("id_forma_pagamento")]
    public int IdFormaPagamento { get; set; }

    [Column("fp_dtCri", TypeName = "DATETIME")]
    public DateTime FpDtCri { get; set; }

    [Column("fp_dtAlt", TypeName = "DATETIME")]
    public DateTime FpDtAlt { get; set; }

    [Column("fp_dtAcs", TypeName = "DATETIME")]
    public DateTime? FpDtAcs { get; set; }

    [Column("fp_desat", TypeName = "NUMERIC(1, 0)")]
    public int? FpDesat { get; set; }

    [Column("fp_desc", TypeName = "varchar(60)")]
    public string FpDesc { get; set; }

    [Column("fp_ordExib", TypeName = "smallint")]
    public short FpOrdExib { get; set; }

    [Column("fp_atalhoTecl", TypeName = "nchar(1)")]
    public string FpAtalhoTecl { get; set; }

    [Column("fp_taxaDesc", TypeName = "varchar(60)")]
    public string FpTaxaDesc { get; set; }

    [Column("fp_taxaData", TypeName = "DATETIME")]
    public DateTime? FpTaxaData { get; set; }

    [Column("fp_taxa0", TypeName = "NUMERIC(6, 3)")]
    public int? FpTaxa0 { get; set; }

    [Column("fp_taxa1", TypeName = "NUMERIC(6, 3)")]
    public double? FpTaxa1 { get; set; }

    [Column("fp_taxa2", TypeName = "NUMERIC(6, 3)")]
    public double? FpTaxa2 { get; set; }

    [Column("fp_taxa3", TypeName = "NUMERIC(6, 3)")]
    public double? FpTaxa3 { get; set; }

    [Column("fp_taxa4", TypeName = "NUMERIC(6, 3)")]
    public double? FpTaxa4 { get; set; }

    [Column("fp_taxa5", TypeName = "NUMERIC(6, 3)")]
    public double? FpTaxa5 { get; set; }

    [Column("fp_taxa6", TypeName = "NUMERIC(6, 3)")]
    public double? FpTaxa6 { get; set; }

    [Column("fp_taxa7", TypeName = "NUMERIC(6, 3)")]
    public double? FpTaxa7 { get; set; }

    [Column("fp_taxa8", TypeName = "NUMERIC(6, 3)")]
    public double? FpTaxa8 { get; set; }

    [Column("fp_taxa9", TypeName = "NUMERIC(6, 3)")]
    public double? FpTaxa9 { get; set; }

    [Column("fp_taxa10", TypeName = "NUMERIC(6, 3)")]
    public double? FpTaxa10 { get; set; }

    [Column("fp_taxa11", TypeName = "NUMERIC(6, 3)")]
    public double? FpTaxa11 { get; set; }

    [Column("fp_taxa12", TypeName = "NUMERIC(6, 3)")]
    public double? FpTaxa12 { get; set; }

    [Column("fp_vlrMin", TypeName = "NUMERIC(13, 2)")]
    public double? FpVlrMin { get; set; }

    [Column("fp_vlrMax", TypeName = "NUMERIC(13, 2)")]
    public double? FpVlrMax { get; set; }

    [Column("fp_parcMin", TypeName = "smallint")]
    public short FpParcMin { get; set; }

    [Column("fp_parcMax", TypeName = "smallint")]
    public short FpParcMax { get; set; }

    [Column("fp_intParcBase", TypeName = "smallint")]
    public short FpIntParcBase { get; set; }

    [Column("fp_nfeIndPag", TypeName = "INT")]
    public int FpNfeIndPag { get; set; }

    [Column("fp_nfeTipoPag", TypeName = "INT")]
    public int FpNfeTipoPag { get; set; }

    [Column("fp_nfeTipoIntegr", TypeName = "tinyint")]
    public byte FpNfeTipoIntegr { get; set; }

    [Column("fp_canc", TypeName = "NUMERIC(1, 0)")]
    public int? FpCanc { get; set; }

    [Column("fk_tb_rede")]
    public int? FkTbRede { get; set; }

    [ForeignKey("FkTbRede")]
    [InverseProperty("TbFormaPagamento")]
    public virtual TbRede FkTbRedeNavigation { get; set; }

    [InverseProperty("FkTbFormaPagamentoNavigation")]
    public virtual ICollection<TbSubFormaPagamento> TbSubFormaPagamento { get; set; } = new List<TbSubFormaPagamento>();
}