// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_marca_produto")]
[Index("FkTbRede", Name = "ifk_tb_rede_tb_marca_produto")]
public partial class TbMarcaProduto
{
    [Key]
    [Column("id_marca_produto")]
    public int IdMarcaProduto { get; set; }

    [Column("mp_dtCri", TypeName = "DATETIME")]
    public DateTime MpDtCri { get; set; }

    [Column("mp_dtAlt", TypeName = "DATETIME")]
    public DateTime MpDtAlt { get; set; }

    [Column("mp_dtAcs", TypeName = "DATETIME")]
    public DateTime? MpDtAcs { get; set; }

    [Column("mp_desat")]
    public int? MpDesat { get; set; }

    [Column("mp_desc", TypeName = "varchar(48)")]
    public string MpDesc { get; set; }

    [Column("fk_tb_rede")]
    public int? FkTbRede { get; set; }

    [ForeignKey("FkTbRede")]
    [InverseProperty("TbMarcaProduto")]
    public virtual TbRede FkTbRedeNavigation { get; set; }

    [InverseProperty("FkTbMatrizNavigation")]
    public virtual ICollection<TbEst> TbEst { get; set; } = new List<TbEst>();

    [InverseProperty("FkTbMarcaProdutoNavigation")]
    public virtual ICollection<TbProduto> TbProduto { get; set; } = new List<TbProduto>();
}