// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_movimentacao_impressao")]
[Index("FkTbMovimentacao", Name = "ifk_tb_movimentacao_tb_movimentacao_impressao")]
public partial class TbMovimentacaoImpressao
{
    [Key]
    [Column("id_movimentacao_impressao")]
    public int IdMovimentacaoImpressao { get; set; }

    [Column("mi_dtCri", TypeName = "DATETIME")]
    public DateTime MiDtCri { get; set; }

    [Column("mi_dtAlt", TypeName = "DATETIME")]
    public DateTime MiDtAlt { get; set; }

    [Column("mi_dtAcs", TypeName = "DATETIME")]
    public DateTime? MiDtAcs { get; set; }

    [Column("mi_tipo", TypeName = "tinyint")]
    public byte MiTipo { get; set; }

    [Column("mi_pdf")]
    public byte[] MiPdf { get; set; }

    [Column("mi_dcanc", TypeName = "NUMERIC(1, 0)")]
    public decimal? MiDcanc { get; set; }

    [Column("fk_tb_movimentacao")]
    public int? FkTbMovimentacao { get; set; }

    [ForeignKey("FkTbMovimentacao")]
    [InverseProperty("TbMovimentacaoImpressao")]
    public virtual TbMovimentacao FkTbMovimentacaoNavigation { get; set; }
}