// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_nfe_enviada_filial")]
[Index("FkTbNfe", Name = "ifk_tb_nfe_tb_nfe_enviada_filial")]
[Index("FkTbPdv", Name = "ifk_tb_pdv_tb_nfe_enviada_filial")]
public partial class TbNfeEnviadaFilial
{
    [Key]
    [Column("id_nfe_enviada_filial")]
    public int IdNfeEnviadaFilial { get; set; }

    [Column("nef_dtCri", TypeName = "DATETIME")]
    public DateTime NefDtCri { get; set; }

    [Column("nef_dtAlt", TypeName = "DATETIME")]
    public DateTime NefDtAlt { get; set; }

    [Column("nef_dtAcs", TypeName = "DATETIME")]
    public DateTime? NefDtAcs { get; set; }

    [Column("nef_desat", TypeName = "NUMERIC(1, 0)")]
    public decimal? NefDesat { get; set; }

    [Column("fk_tb_pdv")]
    public int? FkTbPdv { get; set; }

    [Column("fk_tb_nfe")]
    public int? FkTbNfe { get; set; }

    [ForeignKey("FkTbNfe")]
    [InverseProperty("TbNfeEnviadaFilial")]
    public virtual TbNfe FkTbNfeNavigation { get; set; }

    [ForeignKey("FkTbPdv")]
    [InverseProperty("TbNfeEnviadaFilial")]
    public virtual TbPdv FkTbPdvNavigation { get; set; }
}