// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_produto")]
[Index("FkTbAtor", Name = "ifk_tb_ator_tb_produto")]
[Index("FkTbCategoriaProduto", Name = "ifk_tb_categoria_produto_tb_produto")]
[Index("FkTbEst", Name = "ifk_tb_est_tb_produto")]
[Index("FkTbMarcaProduto", Name = "ifk_tb_marca_produto_tb_produto")]
[Index("FkTbNcm", Name = "ifk_tb_ncm_tb_produto")]
[Index("FkTbRede", Name = "ifk_tb_rede_tb_produto")]
[Index("FkTbRelacaoProdutoCadastroXml", Name = "ifk_tb_relacao_produto_cadastro_XML_tb_produto")]
[Index("FkTbSubcategoriaProduto", Name = "ifk_tb_subcategoria_produto_tb_produto")]
public partial class TbProduto
{
    [Key]
    [Column("id_produto")]
    public int IdProduto { get; set; }

    [Column("pd_dtCri", TypeName = "DATETIME")]
    public DateTime PdDtCri { get; set; }

    [Column("pd_dtAlt", TypeName = "DATETIME")]
    public DateTime PdDtAlt { get; set; }

    [Column("pd_desat", TypeName = "NUMERIC(1, 0)")]
    public int? PdDesat { get; set; }

    [Column("pd_genero", TypeName = "tinyint")]
    public byte PdGenero { get; set; }

    [Column("pd_unMedCom", TypeName = "tinyint")]
    public byte PdUnMedCom { get; set; }

    [Column("pd_codRef", TypeName = "bigint")]
    public long PdCodRef { get; set; }

    [Column("pd_codRefStr", TypeName = "varchar(20)")]
    public string PdCodRefStr { get; set; }

    [Column("pd_barras", TypeName = "varchar(512)")]
    public string PdBarras { get; set; }

    [Column("pd_impRef", TypeName = "varchar(60)")]
    public string PdImpRef { get; set; }

    [Column("pd_proTipo", TypeName = "tinyint")]
    public byte PdProTipo { get; set; }

    [Column("pd_especie", TypeName = "tinyint")]
    public byte PdEspecie { get; set; }

    [Column("pd_estTot", TypeName = "NUMERIC(13, 3)")]
    public int? PdEstTot { get; set; }

    [Column("pd_invend", TypeName = "NUMERIC(1, 0)")]
    public int? PdInvend { get; set; }

    [Column("pd_descCurta", TypeName = "varchar(25)")]
    public string PdDescCurta { get; set; }

    [Column("pd_desc", TypeName = "varchar(120)")]
    public string PdDesc { get; set; }

    [Column("pd_fxEta", TypeName = "tinyint")]
    public byte PdFxEta { get; set; }

    [Column("pd_vlrUnComBase", TypeName = "NUMERIC(13, 2)")]
    public int? PdVlrUnComBase { get; set; }

    [Column("pd_cstUnComBase", TypeName = "NUMERIC(13, 2)")]
    public int? PdCstUnComBase { get; set; }

    [Column("pd_estMinBase", TypeName = "NUMERIC(13, 3)")]
    public int? PdEstMinBase { get; set; }

    [Column("pd_estMaxBase", TypeName = "NUMERIC(13, 3)")]
    public int? PdEstMaxBase { get; set; }

    [Column("pd_nfeProdOrigem", TypeName = "tinyint")]
    public byte PdNfeProdOrigem { get; set; }

    [Column("pd_nfeCsosn", TypeName = "smallint")]
    public short PdNfeCsosn { get; set; }

    [Column("pd_vend", TypeName = "NUMERIC(1, 0)")]
    public int? PdVend { get; set; }

    [Column("pd_tmpStr")]
    public string PdTmpStr { get; set; }

    [Column("pd_ativo", TypeName = "NUMERIC(1, 0)")]
    public int? PdAtivo { get; set; }

    [Column("fk_tb_est")]
    public int? FkTbEst { get; set; }

    [Column("fk_tb_rede")]
    public int? FkTbRede { get; set; }

    [Column("fk_tb_ncm")]
    public int? FkTbNcm { get; set; }

    [Column("fk_tb_ator")]
    public int? FkTbAtor { get; set; }

    [Column("fk_tb_relacao_produto_cadastro_XML")]
    public int? FkTbRelacaoProdutoCadastroXml { get; set; }

    [Column("fk_tb_marca_produto")]
    public int? FkTbMarcaProduto { get; set; }

    [Column("fk_tb_subcategoria_produto")]
    public int? FkTbSubcategoriaProduto { get; set; }

    [Column("fk_tb_categoria_produto")]
    public int? FkTbCategoriaProduto { get; set; }

    [ForeignKey("FkTbAtor")]
    [InverseProperty("TbProduto")]
    public virtual TbAtor FkTbAtorNavigation { get; set; }

    [ForeignKey("FkTbCategoriaProduto")]
    [InverseProperty("TbProduto")]
    public virtual TbCategoriaProduto FkTbCategoriaProdutoNavigation { get; set; }

    [ForeignKey("FkTbEst")]
    [InverseProperty("TbProduto")]
    public virtual TbEst FkTbEstNavigation { get; set; }

    [ForeignKey("FkTbMarcaProduto")]
    [InverseProperty("TbProduto")]
    public virtual TbMarcaProduto FkTbMarcaProdutoNavigation { get; set; }

    [ForeignKey("FkTbNcm")]
    [InverseProperty("TbProduto")]
    public virtual TbNcm FkTbNcmNavigation { get; set; }

    [ForeignKey("FkTbRede")]
    [InverseProperty("TbProduto")]
    public virtual TbRede FkTbRedeNavigation { get; set; }

    [ForeignKey("FkTbRelacaoProdutoCadastroXml")]
    [InverseProperty("TbProduto")]
    public virtual TbRelacaoProdutoCadastroXml FkTbRelacaoProdutoCadastroXmlNavigation { get; set; }

    [ForeignKey("FkTbSubcategoriaProduto")]
    [InverseProperty("TbProduto")]
    public virtual TbSubcategoriaProduto FkTbSubcategoriaProdutoNavigation { get; set; }

    [InverseProperty("FkTbProdutoNavigation")]
    public virtual ICollection<TbCodigoProduto> TbCodigoProduto { get; set; } = new List<TbCodigoProduto>();

    [InverseProperty("FkTbProdutoNavigation")]
    public virtual ICollection<TbMovimentacaoProduto> TbMovimentacaoProduto { get; set; } = new List<TbMovimentacaoProduto>();

    [InverseProperty("FkTbProdutoNavigation")]
    public virtual ICollection<TbProdutoFilial> TbProdutoFilial { get; set; } = new List<TbProdutoFilial>();

    [InverseProperty("FkTbProdutoNavigation")]
    public virtual ICollection<TbRelacaoProdutoCadastroXml> TbRelacaoProdutoCadastroXml { get; set; } = new List<TbRelacaoProdutoCadastroXml>();
}