// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_produto_filial")]
[Index("FkTbAtor", Name = "ifk_tb_ator_tb_produto_filial")]
[Index("FkTbProduto", Name = "ifk_tb_produto_tb_produto_filial")]
public partial class TbProdutoFilial
{
    [Key]
    [Column("id_produto_filial")]
    public int IdProdutoFilial { get; set; }

    [Column("pf_codRef", TypeName = "bigint")]
    public long PfCodRef { get; set; }

    [Column("pf_desc", TypeName = "varchar(120)")]
    public string PfDesc { get; set; }

    [Column("pf_descCurta", TypeName = "varchar(25)")]
    public string PfDescCurta { get; set; }

    [Column("pf_proTipo", TypeName = "tinyint")]
    public byte PfProTipo { get; set; }

    [Column("pf_unMedCom", TypeName = "tinyint")]
    public byte PfUnMedCom { get; set; }

    [Column("pf_dtCri", TypeName = "DATETIME")]
    public DateTime PfDtCri { get; set; }

    [Column("pf_dtAlt", TypeName = "DATETIME")]
    public DateTime PfDtAlt { get; set; }

    [Column("pf_dtAcs", TypeName = "DATETIME")]
    public DateTime? PfDtAcs { get; set; }

    [Column("pf_atorFil")]
    public int? PfAtorFil { get; set; }

    [Column("pf_vlrUnCom", TypeName = "NUMERIC(13, 2)")]
    public int? PfVlrUnCom { get; set; }

    [Column("pf_cstUnCom", TypeName = "NUMERIC(13, 2)")]
    public int? PfCstUnCom { get; set; }

    [Column("pf_estMin", TypeName = "NUMERIC(13, 2)")]
    public int? PfEstMin { get; set; }

    [Column("pf_estMax", TypeName = "money")]
    public int? PfEstMax { get; set; }

    [Column("pf_est", TypeName = "NUMERIC(13, 3)")]
    public int? PfEst { get; set; }

    [Column("pf_desat", TypeName = "NUMERIC(1, 0)")]
    public int? PfDesat { get; set; }

    [Column("pf_canc", TypeName = "NUMERIC(1, 0)")]
    public int? PfCanc { get; set; }

    [Column("fk_tb_produto")]
    public int? FkTbProduto { get; set; }

    [Column("fk_tb_ator")]
    public int? FkTbAtor { get; set; }

    [ForeignKey("FkTbAtor")]
    [InverseProperty("TbProdutoFilial")]
    public virtual TbAtor FkTbAtorNavigation { get; set; }

    [ForeignKey("FkTbProduto")]
    [InverseProperty("TbProdutoFilial")]
    public virtual TbProduto FkTbProdutoNavigation { get; set; }

    [InverseProperty("FkTbProdutoFilialNavigation")]
    public virtual ICollection<TbRelacaoProdutoCadastroXml> TbRelacaoProdutoCadastroXml { get; set; } = new List<TbRelacaoProdutoCadastroXml>();
}