// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_resEventoNFe")]
[Index("FkTbAtor", Name = "ifk_tb_ator_tb_resEventoNFe")]
public partial class TbResEventoNfe
{
    [Key]
    [Column("id_resEventoNFe")]
    public int IdResEventoNfe { get; set; }

    [Column("ref_cnpj", TypeName = "varchar(18)")]
    public string RefCnpj { get; set; }

    [Column("ref_cpf", TypeName = "varchar(14)")]
    public string RefCpf { get; set; }

    [Column("ref_nfeChave", TypeName = "varchar(50)")]
    public string RefNfeChave { get; set; }

    [Column("ref_nfeVersao", TypeName = "NUMERIC(6, 3)")]
    public decimal? RefNfeVersao { get; set; }

    [Column("ref_dtCri", TypeName = "DATETIME")]
    public DateTime RefDtCri { get; set; }

    [Column("ref_dtAlt", TypeName = "DATETIME")]
    public DateTime RefDtAlt { get; set; }

    [Column("ref_dtAcs", TypeName = "DATETIME")]
    public DateTime? RefDtAcs { get; set; }

    [Column("ref_nsu", TypeName = "bigint")]
    public long RefNsu { get; set; }

    [Column("ref_codOrg", TypeName = "smallint")]
    public short RefCodOrg { get; set; }

    [Column("ref_dtEvt", TypeName = "TIMESTAMP(8)")]
    public DateTime RefDtEvt { get; set; }

    [Column("ref_sTpEvt", TypeName = "INT")]
    public int RefSTpEvt { get; set; }

    [Column("ref_numSeqEvt", TypeName = "smallint")]
    public short RefNumSeqEvt { get; set; }

    [Column("ref_descEvt", TypeName = "varchar(60)")]
    public string RefDescEvt { get; set; }

    [Column("ref_nfeNumProtEvt", TypeName = "varchar(15)")]
    public string RefNfeNumProtEvt { get; set; }

    [Column("fk_tb_ator")]
    public int? FkTbAtor { get; set; }

    [ForeignKey("FkTbAtor")]
    [InverseProperty("TbResEventoNfe")]
    public virtual TbAtor FkTbAtorNavigation { get; set; }
}