// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_regioes_br")]
[Index("FkTbPais", Name = "ifk_tb_pais_tb_regioes_br")]
public partial class TbRegioesBr
{
    [Key]
    [Column("id_regioes_br")]
    public int IdRegioesBr { get; set; }

    [Column("rb_desat", TypeName = "NUMERIC(1, 0)")]
    public int? RbDesat { get; set; }

    [Column("rb_id", TypeName = "tinyint")]
    public byte? RbId { get; set; }

    [Column("rb_sigla", TypeName = "varchar(2)")]
    public string RbSigla { get; set; }

    [Column("rb_nome", TypeName = "varchar(12)")]
    public string RbNome { get; set; }

    [Column("fk_tb_pais")]
    public int? FkTbPais { get; set; }

    [ForeignKey("FkTbPais")]
    [InverseProperty("TbRegioesBr")]
    public virtual TbPais FkTbPaisNavigation { get; set; }

    [InverseProperty("FkTbRegioesBrNavigation")]
    public virtual ICollection<TbEstadosBr> TbEstadosBr { get; set; } = new List<TbEstadosBr>();
}