// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_secao_produto")]
[Index("FkTbRede", Name = "ifk_tb_rede_tb_secao_produto")]
public partial class TbSecaoProduto
{
    [Key]
    [Column("id_secao_produto")]
    public int IdSecaoProduto { get; set; }

    [Column("sp_dtCri", TypeName = "DATETIME")]
    public DateTime SpDtCri { get; set; }

    [Column("sp_dtAlt", TypeName = "DATETIME")]
    public DateTime SpDtAlt { get; set; }

    [Column("sp_dtAcs", TypeName = "DATETIME")]
    public DateTime? SpDtAcs { get; set; }

    [Column("sp_desat", TypeName = "NUMERIC(1, 0)")]
    public int? SpDesat { get; set; }

    [Column("sp_desc", TypeName = "varchar(48)")]
    public string SpDesc { get; set; }

    [Column("fk_tb_rede")]
    public int? FkTbRede { get; set; }

    [ForeignKey("FkTbRede")]
    [InverseProperty("TbSecaoProduto")]
    public virtual TbRede FkTbRedeNavigation { get; set; }

    [InverseProperty("FkTbSecaoProdutoNavigation")]
    public virtual ICollection<TbCategoriaProduto> TbCategoriaProduto { get; set; } = new List<TbCategoriaProduto>();
}