// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_Sytem.API.Models;

[Table("tb_sub_forma_pagamento")]
[Index("FkTbFormaPagamento", Name = "ifk_tb_forma_pagamento_tb_sub_forma_pagamento")]
public partial class TbSubFormaPagamento
{
    [Key]
    [Column("id_sub_forma_pagamento")]
    public int IdSubFormaPagamento { get; set; }

    [Column("sfp_dtCri", TypeName = "DATETIME")]
    public DateTime SfpDtCri { get; set; }

    [Column("sfp_dtAlt", TypeName = "DATETIME")]
    public DateTime SfpDtAlt { get; set; }

    [Column("sfp_dtAcs", TypeName = "DATETIME")]
    public DateTime? SfpDtAcs { get; set; }

    [Column("sfp_desat", TypeName = "NUMERIC(1, 0)")]
    public int? SfpDesat { get; set; }

    [Column("sfp_desc", TypeName = "varchar(60)")]
    public string SfpDesc { get; set; }

    [Column("sfp_ordExib", TypeName = "smallint")]
    public short SfpOrdExib { get; set; }

    [Column("sfp_atalhoTecl", TypeName = "nchar(1)")]
    public string SfpAtalhoTecl { get; set; }

    [Column("sfp_intParc", TypeName = "smallint")]
    public short SfpIntParc { get; set; }

    [Column("sfp_nfeTipoBand", TypeName = "tinyint")]
    public byte SfpNfeTipoBand { get; set; }

    [Column("fk_tb_forma_pagamento")]
    public int? FkTbFormaPagamento { get; set; }

    [ForeignKey("FkTbFormaPagamento")]
    [InverseProperty("TbSubFormaPagamento")]
    public virtual TbFormaPagamento FkTbFormaPagamentoNavigation { get; set; }

    [InverseProperty("FkTbSubFormaPagamentoNavigation")]
    public virtual ICollection<TbMovimentacaoPagamento> TbMovimentacaoPagamento { get; set; } = new List<TbMovimentacaoPagamento>();

    [InverseProperty("FkTbSubFormaPagamentoNavigation")]
    public virtual ICollection<TbMovimentacaoPagamentoParcela> TbMovimentacaoPagamentoParcela { get; set; } = new List<TbMovimentacaoPagamentoParcela>();
}